### PR TITLE
Fixed styling

### PR DESCRIPTION
**Pull request by barfittc**
Upped to version 0.10.0

Rearranged style of quickSelect
I move the selectors to a paper-dropdown-menu, in the top area, along with the next/previous month buttons. 
  On a side note. There's some old used CSS classes that need to get filtered and removed.

Removed dependency to autonotify_observe
I removed the autonotify_observe because it seems more logical to have a more general library (less dependencies the better!), and because autonotify_observe was crashing everything for me..

### CODE REVIEW

**Comment by dam0vm3nt** [comment]
For this single component I'm positive to get rid of `autonotify`. 

But can you tell me your issues with autonotify ? I'm using it in a pretty big project without any problem since two months now.

**Comment by barfittc** [comment]
The main issue was, I was having trouble getting dependencies to work with it. It started when this one showed up. https://github.com/dart-lang/polymer-dart/issues/665 Since then, I haven't been able to get a `pub get` or `pub upgrade` working with `autonotify` included, with any version of `autonotify`.

**Comment by dam0vm3nt** [comment]
So after all seams that your problems were not related to `autonotify` at all! 
BTW https://github.com/dart-lang/polymer-dart/issues/665 seams to be fixed now.

Whatever I was already thinking of removing `autonotify` from this component for those reasons you already mentioned. But I was indecided because I feared that eventually I was going to miss it.

If there will be the case I'm sure you will help me to restore it!

I'm going to merge this by now. Wouldn't you mind if I enlist you in the `pubspec` authors ? Let me know.

**Comment by barfittc** [comment]
Yeah, you can list me in the pubspec. 
I can help with whatever pops up in the future.

**Comment by dam0vm3nt** [comment]
k, I'm going to make `quickSelect` the default behaviour, introducing the `disable-quick-select` attribute.
I think this will be the most common setup. Do you mind it ?

**Comment by dam0vm3nt** [comment]
ops, can't find your contact info anywhere. Will you please add yourself to the pubspec next time ?

**Comment by barfittc** [comment]
No I do not mind, I was debating on that anyway.

Here's my info, I don't know how I would add multiple authors.
Chris Barfitt barfittc@gmail.com

**Comment by dam0vm3nt** [comment]
done

Il giorno ven 5 feb 2016 alle ore 01:59 barfittc notifications@github.com
ha scritto:

**Pull request merged**
