### PR TITLE
Material Design

### PR DESCRIPTION
**Pull request by barfittc**
Updated the styling to match the Material Designed date picker on Android
Separated the overlay and overlay variables for ease of coding
added a quick change property to quickly switch between months and years

### CODE REVIEW

**Comment by dam0vm3nt** [comment]
great job, definitively.

**Comment by barfittc** [comment]
Thanks. I wouldn't of been able to do it without the structure you already
created.

**Comment by dam0vm3nt** [comment]
Tnx. It was such a basic component that I was really surprised it was not already there (back in the `polymer-0.x` times), so I made it.

btw, in "quick select" mode I have noted you choosed to use a `paper-input` but you can't use it because as soon as it gets focus the view switches and list selectors for months/years are shown. 
I really like this behavior but I wonder if the `paper-input` is actually usefull at this point.

**Comment by barfittc** [comment]
I know, I'm surprised it's not included with the elements package.
I picked paper-input because it makes makes it obvious (I think) that's
where you would click to activate the selector. I'm open to suggestions.

**Pull request merged**
